# Generated by Django 6.0.dev20250516135617 on 2025-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('relationship', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HIJO', 'Hijo/a'), ('HERMANO', 'Hermano/a'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Relación')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Miembro de la Familia',
                'verbose_name_plural': 'Miembros de la Familia',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
